version: '3.8'

services:
  backend:
    image: balagi/chaatra-backend:latest
    ports:
      - "8081:8081"

  frontend:
    image: balagi/chaatra-frontend:latest
    ports:
      - "3000:3000"  
    depends_on:
      - backend
