version: '3.8'

services:
  backend:
    image: balagi/chaatra-backend:latest
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  frontend:
    image: balagi/chaatra-frontend:latest
    ports:
      - "3000:3000"  
    environment:
      - REACT_APP_API_BASE_URL=http://chaatra.co/api
    depends_on:
      - backend
