version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/go/src/app
    environment:
      - GO_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /frontend/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend