name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/chaatra-backend:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/chaatra-backend:latest ./backend
        
    - name: List Docker Images 
      run: | 
        docker images
    
    - name: Push Images
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/chaatra-backend:${{ github.sha }} || exit 1
        docker push ${{ secrets.DOCKER_USERNAME }}/chaatra-backend:latest || exit 1

  build-and-push-frontend:
    runs-on: ubuntu-latest
    needs: build-and-push-backend
    steps:
    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image for frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/chaatra-frontend:${{ github.sha }} -t ${{ secrets.DOCKER_USERNAME }}/chaatra-rontend:latest ./frontend
        docker push ${{ secrets.DOCKER_USERNAME }}/chaatra-frontend:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/chaatra-frontend:latest
